from app.models.usuario import Usuario
from app.models.estudiante import Estudiante
from app.models.docente import Docente
from app.models.clase import Clase
from app.models.nivel import Nivel
from app.models.progreso_nivel import ProgresoNivel
from app.models.actividad import Actividad
from app.models.calificacion import Calificacion
from app.models.insignia import Insignia
from app.models.estudiante_insignia import EstudianteInsignia
from app.models.recompensa import Recompensa
from app.models.canje import Canje
from app.models.configuracion_gamificacion import ConfiguracionGamificacion